### ISSUE TITLE
From the perspective of one client, they have 45 trains, but it shows everyone else having 20

### ISSUE THREAD

**Issue by Deriboy** [cs340tabyu/CS340Summer2017#19]

**Comment by Deriboy** [comment]
![image](https://user-images.githubusercontent.com/3218615/28979537-740fc9b2-7907-11e7-930e-75b3f9719105.png)

**Comment by Deriboy** [comment]
![image](https://user-images.githubusercontent.com/3218615/28979619-b915b49a-7907-11e7-99a9-cc5bcf1d130e.png)
from another perspective

**Comment by Glowsquirrel** [comment]
This bug is caused by differing initial trains on the client and server side. For testing purposes, the number of trains for each player on the server side was reduced, but this change was not performed on the client side. Changing the number of starting trains on the server side fixes this, but the best solution would to have both the client and server depend on a field in the common code that dictates not only the number of trains, but any other field that is used as an initial value (such as starting number of train cards).
