### ISSUE TITLE
Login screen doesn't consider changed ip address

### ISSUE THREAD

**Issue by Deriboy** [cs340tabyu/CS340Summer2017#24]
I registered as a user on the ip address of a running server, and then changed the ip address to an invalid one. When I tried to log in at that point it let me, and logged me into the server I registered to previously

**Comment by Glowsquirrel** [comment]
This bug was caused by the client using the first valid IP address to establish a web socket to use with every subsequent network request. Unless it is a successful login, the web socket will now close and new IP addresses will be properly taken into account. (A less costly solution would be to use normal HTTP requests until a successful login, then use only the web socket, but the old handlers have already been removed and most likely will not be re-implemented in the remaining time of this class).
