### ISSUE TITLE
Score is not consistent with number of claimed routes

### ISSUE THREAD

**Issue by jonandrewj** [cs340tabyu/CS340Summer2017#28]
![image](https://user-images.githubusercontent.com/29874842/28979918-0649c886-7909-11e7-92a0-b74c88be471c.png)

Score of 1 with 3 claimed routes....

**Comment by Glowsquirrel** [comment]
This bug was caused by clipping from the border that shows whose turn it current is. The text inside the player views have been resized to better accommodate the information.
![screenshot_1502090494](https://user-images.githubusercontent.com/25395687/29016234-e2f86ee8-7b0e-11e7-983d-077aec496539.png)
