### ISSUE TITLE
Unable to test the Game End Screen because we were unable to make it there without a crash along the way

### ISSUE THREAD

**Issue by jonandrewj** [cs340tabyu/CS340Summer2017#63]
We have seen the end game screen when a client crashes and the other client becomes the winner by default, but we wanted to see the game end legitimately.

**Comment by Glowsquirrel** [comment]
This bug is caused by an observer updating in the time frame that the server ends the game and the client displays the end game screen. After the client receives the end game information, it would overwrite all players' information and would have a race condition between updating their information again and displaying the end. When overwriting, they are given a color again, which now prevents the Resources$NotFoundException from being thrown (as they properly have their color again). A better solution would be to put the end game information in a different structure rather than overwriting what is currently there.
